services:
  - type: web
    name: ppm-backend
    runtime: python
    healthCheckPath: /docs
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_HOST
        sync: false
        placeholder: "Enter hosted MySQL database host URL"
      - key: DB_USER
        sync: false
        placeholder: "Enter database username"
      - key: DB_PASSWORD
        sync: false
        placeholder: "Enter database password"
      - key: DB_NAME
        value: ppm_monitoring
      - key: DB_PORT
        value: "3306"
